remove ffm from arm

diff --git a/server-native/Dockerfile.ubi9 b/server-native/Dockerfile.ubi9
--- a/server-native/Dockerfile.ubi9
+++ b/server-native/Dockerfile.ubi9
@@ -116,13 +116,13 @@ RUN microdnf install -y zip unzip && \
       else \
         echo "Skipping $jarname"; \
       fi; \
-    done
+    done && \
+    echo "Removing jline FFM classes to prevent ForeignFunctionsRuntime error on ARM..." && \
+    find /usr/share/java -name "jline*.jar" -exec zip -d {} 'org/jline/terminal/impl/ffm/*' \; 2>/dev/null || true
 
 # Build native image for the Kafka application
 RUN mkdir /app/kafka; \
     native-image --no-fallback -H:-CheckToolchain --enable-http \
-                                                    --exclude-config ".*jline.*\.jar" "META-INF/native-image/org.jline/jline-terminal-ffm/.*" \
-                                                    --initialize-at-run-time=org.jline.terminal.impl.ffm \
                                                     --enable-https \
                                                     --enable-preview \
                                                     --add-exports org.graalvm.nativeimage.builder/com.oracle.svm.core.configure=ALL-UNNAMED \
